/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ensambladora.de.maquinas;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Proveedor = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_IdProveedor = new javax.swing.JTextField();
        tf_NombreProv = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jb_AgregarProv = new javax.swing.JButton();
        jd_Comercio = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_NumComercio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_NomComercio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_Provee = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        sp_Ingreso = new javax.swing.JSpinner();
        jb_AgregarComercio = new javax.swing.JButton();
        jd_Producto = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_IDProducto = new javax.swing.JTextField();
        tf_Marca = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jd_Maquina = new javax.swing.JDialog();
        jd_Tecnico = new javax.swing.JDialog();
        jd_Reparacion = new javax.swing.JDialog();
        jd_Alquiler = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jb_Proveedor = new javax.swing.JButton();
        jb_Producto = new javax.swing.JButton();
        jb_Comercio = new javax.swing.JButton();
        jb_Tecnico = new javax.swing.JButton();
        jb_Maquina = new javax.swing.JButton();
        jb_Reparacion = new javax.swing.JButton();
        jb_Alquiler = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel2.setText("Proveedor");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel3.setText("ID  Proveedor");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel4.setText("Nombre Proveedor");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel5.setText("Proveedor Placas");

        tf_IdProveedor.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_NombreProv.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placas", "Carcasas" }));

        jb_AgregarProv.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jb_AgregarProv.setText("Agregar");
        jb_AgregarProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_AgregarProvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ProveedorLayout = new javax.swing.GroupLayout(jd_Proveedor.getContentPane());
        jd_Proveedor.getContentPane().setLayout(jd_ProveedorLayout);
        jd_ProveedorLayout.setHorizontalGroup(
            jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProveedorLayout.createSequentialGroup()
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProveedorLayout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(jLabel2))
                    .addGroup(jd_ProveedorLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(144, 144, 144)
                        .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProveedorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jb_AgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jd_ProveedorLayout.setVerticalGroup(
            jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProveedorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addGap(160, 160, 160)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_NombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129)
                .addGroup(jd_ProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jb_AgregarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jLabel6.setText("Comercio");

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel7.setText("Numero de Comercio");

        tf_NumComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel8.setText("Nombre de Comercio");

        tf_NomComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel9.setText("Recaudacion Total");

        jTextField1.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel10.setText("Provee");

        cb_Provee.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        cb_Provee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayorista", "Minorista" }));
        cb_Provee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ProveeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel11.setText("Porcentaje Ingreso");

        sp_Ingreso.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        sp_Ingreso.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 5));

        jb_AgregarComercio.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jb_AgregarComercio.setText("Agregar");

        javax.swing.GroupLayout jd_ComercioLayout = new javax.swing.GroupLayout(jd_Comercio.getContentPane());
        jd_Comercio.getContentPane().setLayout(jd_ComercioLayout);
        jd_ComercioLayout.setHorizontalGroup(
            jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComercioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(tf_NumComercio)
                        .addComponent(tf_NomComercio)
                        .addComponent(jTextField1)
                        .addComponent(cb_Provee, 0, 289, Short.MAX_VALUE))
                    .addComponent(sp_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ComercioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_AgregarComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jd_ComercioLayout.setVerticalGroup(
            jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ComercioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(121, 121, 121)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_NumComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_NomComercio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_Provee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jd_ComercioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_AgregarComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("MS UI Gothic", 0, 48)); // NOI18N
        jLabel12.setText("Producto");

        jLabel13.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel13.setText("ID Producto");

        jLabel14.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel14.setText("Marca");

        jLabel15.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel15.setText("Material");

        jLabel16.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jLabel16.setText("ID Proveedor");

        tf_IDProducto.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        tf_Marca.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jTextField4.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N

        jButton1.setFont(new java.awt.Font("MS UI Gothic", 0, 24)); // NOI18N
        jButton1.setText("Agregar");

        javax.swing.GroupLayout jd_ProductoLayout = new javax.swing.GroupLayout(jd_Producto.getContentPane());
        jd_Producto.getContentPane().setLayout(jd_ProductoLayout);
        jd_ProductoLayout.setHorizontalGroup(
            jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProductoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(110, 110, 110)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_IDProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                        .addComponent(tf_Marca)
                        .addComponent(jTextField4))
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ProductoLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jd_ProductoLayout.setVerticalGroup(
            jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ProductoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel12)
                .addGap(107, 107, 107)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_IDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jd_ProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_MaquinaLayout = new javax.swing.GroupLayout(jd_Maquina.getContentPane());
        jd_Maquina.getContentPane().setLayout(jd_MaquinaLayout);
        jd_MaquinaLayout.setHorizontalGroup(
            jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_MaquinaLayout.setVerticalGroup(
            jd_MaquinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_TecnicoLayout = new javax.swing.GroupLayout(jd_Tecnico.getContentPane());
        jd_Tecnico.getContentPane().setLayout(jd_TecnicoLayout);
        jd_TecnicoLayout.setHorizontalGroup(
            jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_TecnicoLayout.setVerticalGroup(
            jd_TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_ReparacionLayout = new javax.swing.GroupLayout(jd_Reparacion.getContentPane());
        jd_Reparacion.getContentPane().setLayout(jd_ReparacionLayout);
        jd_ReparacionLayout.setHorizontalGroup(
            jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_ReparacionLayout.setVerticalGroup(
            jd_ReparacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_AlquilerLayout = new javax.swing.GroupLayout(jd_Alquiler.getContentPane());
        jd_Alquiler.getContentPane().setLayout(jd_AlquilerLayout);
        jd_AlquilerLayout.setHorizontalGroup(
            jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_AlquilerLayout.setVerticalGroup(
            jd_AlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 1, 48)); // NOI18N
        jLabel1.setText("Compañia de Ensamblaje");

        jb_Proveedor.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Proveedor.setText("Proveedor");
        jb_Proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ProveedorMouseClicked(evt);
            }
        });

        jb_Producto.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Producto.setText("Producto");

        jb_Comercio.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Comercio.setText("Comercio");
        jb_Comercio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ComercioMouseClicked(evt);
            }
        });

        jb_Tecnico.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Tecnico.setText("Tecnico");

        jb_Maquina.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Maquina.setText("Maquina");

        jb_Reparacion.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Reparacion.setText("Orden  Reparación");

        jb_Alquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 36)); // NOI18N
        jb_Alquiler.setText("Alquiler de  Maquina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(571, 571, 571))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_Proveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(404, 404, 404)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_Tecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205)
                                .addComponent(jb_Reparacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jb_Comercio)
                                .addGap(294, 294, 294)
                                .addComponent(jb_Maquina))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(jb_Alquiler)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Proveedor)
                    .addComponent(jb_Comercio)
                    .addComponent(jb_Maquina))
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Producto)
                    .addComponent(jb_Tecnico)
                    .addComponent(jb_Reparacion))
                .addGap(103, 103, 103)
                .addComponent(jb_Alquiler)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_AgregarProvMouseClicked
        
    }//GEN-LAST:event_jb_AgregarProvMouseClicked

    private void jb_ProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ProveedorMouseClicked
        jd_Proveedor.pack();
        jd_Proveedor.setModal(true);
        jd_Proveedor.setVisible(true);
        jd_Proveedor.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ProveedorMouseClicked

    private void jb_ComercioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ComercioMouseClicked
        jd_Comercio.pack();
        jd_Comercio.setModal(true);
        jd_Comercio.setVisible(true);
        jd_Comercio.setLocationRelativeTo(null);
    }//GEN-LAST:event_jb_ComercioMouseClicked

    private void cb_ProveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ProveeActionPerformed
        if (cb_Provee.getSelectedIndex()==1) {
            sp_Ingreso.setEnabled(false);
        }else{
            sp_Ingreso.setEnabled(true);
        }
    }//GEN-LAST:event_cb_ProveeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_Provee;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton jb_AgregarComercio;
    private javax.swing.JButton jb_AgregarProv;
    private javax.swing.JButton jb_Alquiler;
    private javax.swing.JButton jb_Comercio;
    private javax.swing.JButton jb_Maquina;
    private javax.swing.JButton jb_Producto;
    private javax.swing.JButton jb_Proveedor;
    private javax.swing.JButton jb_Reparacion;
    private javax.swing.JButton jb_Tecnico;
    private javax.swing.JDialog jd_Alquiler;
    private javax.swing.JDialog jd_Comercio;
    private javax.swing.JDialog jd_Maquina;
    private javax.swing.JDialog jd_Producto;
    private javax.swing.JDialog jd_Proveedor;
    private javax.swing.JDialog jd_Reparacion;
    private javax.swing.JDialog jd_Tecnico;
    private javax.swing.JSpinner sp_Ingreso;
    private javax.swing.JTextField tf_IDProducto;
    private javax.swing.JTextField tf_IdProveedor;
    private javax.swing.JTextField tf_Marca;
    private javax.swing.JTextField tf_NomComercio;
    private javax.swing.JTextField tf_NombreProv;
    private javax.swing.JTextField tf_NumComercio;
    // End of variables declaration//GEN-END:variables
}
